spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 941632909014-n4fjdi4r7ms3smamnso4gsspo4u9e3o0.apps.googleusercontent.com
            client-secret: I9XRIfBqQnNk-HxKxO3bBafj
